# Generated by Django 5.2.7 on 2026-01-02 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, help_text='Harga course'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_instructed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama konten', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi konten')),
                ('video_url', models.URLField(blank=True, help_text='URL video')),
                ('file_attachment', models.CharField(blank=True, help_text='File attachment path', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Urutan konten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Content',
                'verbose_name_plural': 'Course Contents',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(help_text='Role member (student, instructor, etc)', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Member',
                'verbose_name_plural': 'Course Members',
                'ordering': ['-joined_at'],
                'unique_together': {('user_id', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Isi komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.coursecontent')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.coursemember')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
